# Likes Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/Likes

#==================#
#   Vault Config   #
#==================#
# Hook to Vault for economy integration
UseVault: false
# Costs
Cost:
  Like: 500
  Create: 1000

#==================#
#   MySQL Config   #
#==================#
MySQL:
  Server:
    Address: localhost
    Port: 3306
  Database:
    Name: DatabaseName
    User_Name: UserName
    User_Password: UserPassword
    TablePrefix: likes_

#========================#
#   Permissions Config   #
#========================#
# Use Permissions List
Permissions:
- vault
- pex
- superperms
- ops

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1